# ── routes/sandbox_routes.py — Sandbox Refresh: API-to-API tokenized export ──
"""
Provides two sets of endpoints:
  1. PROD-SIDE (any env): Token management + anonymized data export
  2. STAGING-SIDE (staging only): Connection config, refresh, generate, clear

Architecture: Staging calls prod's export endpoint with an encrypted token.
Prod anonymizes data in-memory before returning it. Raw PII never leaves prod.
"""
import os
import uuid
import re
import json
import secrets
import logging
import threading
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, Request
from sqlalchemy.orm import Session
from sqlalchemy import func, inspect as sa_inspect

import models
from database import get_db, engine
from auth import require_super_admin
from crypto import encrypt_token, decrypt_token
from routes._admin_helpers import _get_or_create_sync_settings

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/admin/sandbox", tags=["Sandbox"])

# ── Module-level state ───────────────────────────────────────────────────────
_refresh_lock = threading.Lock()
_refresh_progress = {
    "status": "idle",       # idle | running | done | failed
    "step": "",
    "percent": 0,
    "detail": "",
    "started_at": None,
    "finished_at": None,
    "lead_count": 0,
    "error": None,
}


# ── Helpers ──────────────────────────────────────────────────────────────────

def _is_staging() -> bool:
    """Auto-detect staging via RENDER_EXTERNAL_URL or SANDBOX_ALLOW_SELF_TEST."""
    ext_url = os.getenv("RENDER_EXTERNAL_URL", "")
    if os.getenv("SANDBOX_ALLOW_SELF_TEST", "").lower() in ("true", "1"):
        return True
    return "staging" in ext_url.lower()


def _require_staging():
    """Guard: block staging-only endpoints on production."""
    if not _is_staging():
        raise HTTPException(status_code=403, detail="This feature is only available on staging.")


def _validate_sandbox_token(request: Request, db: Session) -> bool:
    """Validate the X-Sandbox-Token header against the stored encrypted token."""
    token = request.headers.get("X-Sandbox-Token", "")
    if not token:
        raise HTTPException(status_code=401, detail="Missing X-Sandbox-Token header")
    settings = _get_or_create_sync_settings(db)
    if not settings.sandbox_token:
        raise HTTPException(status_code=401, detail="No sandbox token configured on this server")
    try:
        stored_plain = decrypt_token(settings.sandbox_token)
    except Exception:
        raise HTTPException(status_code=500, detail="Failed to decrypt stored sandbox token")
    if not secrets.compare_digest(token, stored_plain):
        raise HTTPException(status_code=401, detail="Invalid sandbox token")
    return True


def _scrub_pii(text_val: str) -> str:
    """Remove emails and phone numbers from free-text fields."""
    if not text_val:
        return text_val
    # Remove emails
    text_val = re.sub(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', '[email]', text_val)
    # Remove phone numbers (7+ digits with optional formatting)
    text_val = re.sub(r'[\+]?[\d\s\-\(\)\.]{7,}', '[phone]', text_val)
    return text_val


# ══════════════════════════════════════════════════════════════════════════════
# PROD-SIDE ENDPOINTS (work on any environment)
# ══════════════════════════════════════════════════════════════════════════════

# ── Token Management ─────────────────────────────────────────────────────────

@router.get("/token/status")
def sandbox_token_status(
    db: Session = Depends(get_db),
    admin: dict = Depends(require_super_admin),
):
    """Check if a sandbox token is configured."""
    settings = _get_or_create_sync_settings(db)
    return {"configured": bool(settings.sandbox_token)}


@router.post("/token/generate")
def generate_sandbox_token(
    db: Session = Depends(get_db),
    admin: dict = Depends(require_super_admin),
):
    """Generate a new sandbox access token. Replaces any existing token."""
    raw_token = f"sb_live_{secrets.token_urlsafe(32)}"
    settings = _get_or_create_sync_settings(db)
    settings.sandbox_token = encrypt_token(raw_token)
    db.commit()
    logger.info(f"Sandbox token generated by {admin.get('email')}")
    return {"success": True, "token": raw_token}


@router.delete("/token")
def revoke_sandbox_token(
    db: Session = Depends(get_db),
    admin: dict = Depends(require_super_admin),
):
    """Revoke the sandbox access token."""
    settings = _get_or_create_sync_settings(db)
    settings.sandbox_token = None
    db.commit()
    logger.info(f"Sandbox token revoked by {admin.get('email')}")
    return {"success": True, "message": "Sandbox token revoked."}


# ── Export Endpoint (token-authenticated) ────────────────────────────────────

# Tables to skip entirely (identity/config — staging has its own)
SKIP_TABLES = {"users", "allowed_users", "salesforce_connections", "nylas_config",
               "user_mailboxes", "alembic_version"}

# Tables to copy as-is (config/metadata, no PII)
COPY_AS_IS = {"pods", "sync_settings", "company_research", "lead_upload_logs"}


def _anonymize_leads(rows: list) -> list:
    """Anonymize lead records in-memory."""
    from faker import Faker
    fake = Faker()
    for r in rows:
        r["first_name"] = fake.first_name()
        r["last_name"] = fake.last_name()
        r["email"] = f"lead_{r.get('id', 'x')[:8]}@staging.test"
        r["phone"] = fake.phone_number() if r.get("phone") else None
        r["phone_secondary"] = None
        r["company"] = fake.company() if r.get("company") else None
        r["title"] = fake.job() if r.get("title") else None
        r["linkedin_url"] = None
        r["person_linkedin"] = None
        r["website"] = None
        r["company_phone"] = None
        r["company_linkedin"] = None
        r["company_street"] = None
        r["company_city"] = fake.city() if r.get("company_city") else None
        r["company_state"] = fake.state_abbr() if r.get("company_state") else None
        r["company_country"] = r.get("company_country")  # keep country
        r["company_postal_code"] = None
        # Scrub research fields
        for f in ["research_company", "research_contact", "research_hypothesis",
                   "research_personalization", "research_hook", "research_channels"]:
            if r.get(f):
                r[f] = _scrub_pii(r[f])
    return rows


def _anonymize_table(table_name: str, rows: list) -> list:
    """Apply table-specific anonymization rules."""
    if table_name == "leads":
        return _anonymize_leads(rows)

    from faker import Faker
    fake = Faker()

    for r in rows:
        if table_name == "notes":
            if r.get("content"):
                r["content"] = _scrub_pii(r["content"])

        elif table_name == "call_logs":
            if r.get("notes"):
                r["notes"] = _scrub_pii(r["notes"])

        elif table_name == "login_logs":
            r["email"] = f"user_{r.get('user_id', 'x')[:6]}@staging.test"
            r["ip_address"] = f"192.168.0.{hash(r.get('id', '')) % 255}"
            r["name"] = fake.name()
            r["user_agent"] = "Mozilla/5.0 (Staging)"

        elif table_name == "lead_email_activity":
            r["from_email"] = f"from_{r.get('id', 'x')[:6]}@staging.test"
            r["to_email"] = f"to_{r.get('id', 'x')[:6]}@staging.test"
            r["subject"] = "Staging email subject"
            if r.get("body_preview"):
                r["body_preview"] = _scrub_pii(r["body_preview"][:200])

        elif table_name == "salesforce_integration_logs":
            r["first_name"] = fake.first_name() if r.get("first_name") else None
            r["last_name"] = fake.last_name() if r.get("last_name") else None
            r["email"] = f"sf_{r.get('id', 'x')[:6]}@staging.test" if r.get("email") else None

        elif table_name in ("user_activity_logs", "user_activity_daily_summary"):
            r["user_email"] = f"user_{r.get('user_id', 'x')[:6]}@staging.test" if r.get("user_email") else None
            r["user_name"] = fake.name() if r.get("user_name") else None

        elif table_name == "feedback":
            r["user_email"] = f"fb_{r.get('id', 'x')[:6]}@staging.test" if r.get("user_email") else None
            r["message"] = _scrub_pii(r.get("message", ""))

        elif table_name == "dialer_calls":
            r["phone_number"] = fake.phone_number() if r.get("phone_number") else None
            if r.get("notes"):
                r["notes"] = _scrub_pii(r["notes"])
            if r.get("transcript"):
                r["transcript"] = _scrub_pii(r["transcript"])

        elif table_name == "email_threads":
            pass  # Only IDs and timestamps, no PII

        elif table_name == "lead_attachments":
            pass  # File metadata only, no PII in columns

    return rows


@router.get("/export/tables")
def export_table_list(
    request: Request,
    db: Session = Depends(get_db),
):
    """Return list of exportable tables + row counts. Token-authenticated."""
    _validate_sandbox_token(request, db)
    inspector = sa_inspect(engine)
    available_tables = inspector.get_table_names()
    tables = {}
    for table_name in available_tables:
        if table_name in SKIP_TABLES:
            continue
        try:
            table_obj = models.Base.metadata.tables.get(table_name)
            if table_obj is not None:
                count = db.execute(func.count().select_from(table_obj)).scalar()
                tables[table_name] = count
        except Exception:
            tables[table_name] = -1
    return {
        "success": True,
        "tables": tables,
        "total_records": sum(v for v in tables.values() if v > 0),
    }


@router.get("/export/table/{table_name}")
def export_single_table(
    table_name: str,
    request: Request,
    db: Session = Depends(get_db),
):
    """Export a single table, anonymized. Token-authenticated."""
    _validate_sandbox_token(request, db)
    if table_name in SKIP_TABLES:
        raise HTTPException(status_code=400, detail=f"Table '{table_name}' is not exportable.")

    table_obj = models.Base.metadata.tables.get(table_name)
    if table_obj is None:
        raise HTTPException(status_code=404, detail=f"Table '{table_name}' not found.")

    try:
        result = db.execute(table_obj.select())
        columns = result.keys()
        rows = [dict(zip(columns, row)) for row in result.fetchall()]
        for row in rows:
            for k, v in row.items():
                if isinstance(v, datetime):
                    row[k] = v.isoformat()
        if table_name not in COPY_AS_IS:
            rows = _anonymize_table(table_name, rows)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Export failed for table '{table_name}': {str(e)}")

    return {"success": True, "table": table_name, "row_count": len(rows), "rows": rows}


@router.get("/export")
def export_anonymized_data(
    request: Request,
    db: Session = Depends(get_db),
):
    """Legacy: returns table list + counts only. Use /export/table/{name} for per-table data."""
    _validate_sandbox_token(request, db)
    inspector = sa_inspect(engine)
    available_tables = [t for t in inspector.get_table_names() if t not in SKIP_TABLES]
    return {
        "success": True,
        "exported_at": datetime.now(timezone.utc).isoformat(),
        "tables": available_tables,
        "message": "Use GET /export/table/{table_name} for per-table data.",
    }


@router.get("/export/count")
def export_record_count(
    request: Request,
    db: Session = Depends(get_db),
):
    """Quick count of exportable records (for ETA estimation). Token-authenticated."""
    _validate_sandbox_token(request, db)

    inspector = sa_inspect(engine)
    available_tables = inspector.get_table_names()
    counts = {}

    for table_name in available_tables:
        if table_name in SKIP_TABLES:
            continue
        try:
            table_obj = models.Base.metadata.tables.get(table_name)
            if table_obj is not None:
                count = db.execute(func.count().select_from(table_obj)).scalar()
                counts[table_name] = count
        except Exception:
            continue

    return {
        "success": True,
        "counts": counts,
        "total_records": sum(counts.values()),
    }


# ══════════════════════════════════════════════════════════════════════════════
# STAGING-SIDE ENDPOINTS (staging only — blocked on production)
# ══════════════════════════════════════════════════════════════════════════════

# ── Connection Management ────────────────────────────────────────────────────

@router.post("/connection")
def save_connection(
    body: dict,
    db: Session = Depends(get_db),
    admin: dict = Depends(require_super_admin),
):
    """Save production URL + sandbox token (staging only)."""
    _require_staging()
    prod_url = (body.get("prod_url") or "").strip().rstrip("/")
    token = (body.get("token") or "").strip()

    if not prod_url or not token:
        raise HTTPException(status_code=400, detail="Production URL and sandbox token are required.")

    # Guard: prevent connecting to self
    my_url = os.getenv("RENDER_EXTERNAL_URL", "").strip().rstrip("/")
    allow_self = os.getenv("SANDBOX_ALLOW_SELF_TEST", "").lower() in ("true", "1")
    if my_url and prod_url.rstrip("/") == my_url and not allow_self:
        raise HTTPException(status_code=400, detail="This is the staging URL, not production.")

    # Test the connection by calling prod's token status — must return JSON
    import httpx
    try:
        resp = httpx.get(
            f"{prod_url}/api/admin/sandbox/export/count",
            headers={"X-Sandbox-Token": token},
            timeout=10,
        )
        if resp.status_code == 401:
            raise HTTPException(status_code=400, detail="Invalid token — production rejected it.")
        if resp.status_code != 200:
            raise HTTPException(status_code=400, detail=f"Production returned status {resp.status_code}")
        # Validate it's actually an API (not a frontend serving HTML)
        content_type = resp.headers.get("content-type", "")
        if "text/html" in content_type:
            raise HTTPException(
                status_code=400,
                detail=(
                    "The URL returned HTML instead of JSON — it points to a frontend, not the backend API. "
                    "Use the direct backend API URL (e.g. https://api.alternatecrm.com)."
                )
            )
        try:
            resp.json()
        except Exception:
            raise HTTPException(status_code=400, detail="Production did not return valid JSON. Check the URL.")
    except httpx.ConnectError:
        raise HTTPException(status_code=400, detail="Could not reach production. Check the URL.")
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Connection test failed: {str(e)}")

    # Store encrypted
    settings = _get_or_create_sync_settings(db)
    settings.sandbox_prod_url = encrypt_token(prod_url)
    settings.sandbox_prod_token = encrypt_token(token)
    db.commit()

    logger.info(f"Sandbox connection saved by {admin.get('email')}")
    return {"success": True, "message": "Connected to production."}


@router.get("/connection")
def get_connection_status(
    db: Session = Depends(get_db),
    admin: dict = Depends(require_super_admin),
):
    """Check staging's connection to production."""
    _require_staging()
    settings = _get_or_create_sync_settings(db)
    connected = bool(settings.sandbox_prod_url and settings.sandbox_prod_token)

    result = {
        "connected": connected,
        "last_refresh_at": settings.sandbox_last_refresh_at.isoformat() if settings.sandbox_last_refresh_at else None,
        "last_refresh_status": settings.sandbox_last_refresh_status,
        "last_refresh_lead_count": settings.sandbox_refresh_lead_count,
    }

    if connected:
        try:
            result["prod_url"] = decrypt_token(settings.sandbox_prod_url)
        except Exception:
            result["prod_url"] = "(encrypted)"

    return result


@router.delete("/connection")
def clear_connection(
    db: Session = Depends(get_db),
    admin: dict = Depends(require_super_admin),
):
    """Remove the production connection (staging only)."""
    _require_staging()
    settings = _get_or_create_sync_settings(db)
    settings.sandbox_prod_url = None
    settings.sandbox_prod_token = None
    db.commit()
    logger.info(f"Sandbox connection cleared by {admin.get('email')}")
    return {"success": True, "message": "Connection removed."}


# ── Refresh (Mirror Mode) ───────────────────────────────────────────────────

def _do_refresh(prod_url: str, token: str):
    """Background worker: pull anonymized data from prod table-by-table and write to staging DB."""
    global _refresh_progress
    from database import SessionLocal
    import httpx

    _refresh_progress.update(status="running", step="Connecting to production API...",
                             percent=5, error=None, started_at=datetime.now(timezone.utc).isoformat())
    db = SessionLocal()
    hdr = {"X-Sandbox-Token": token}

    def _prod_get(path: str, timeout: int = 30):
        """GET from prod with consistent error handling."""
        resp = httpx.get(f"{prod_url}{path}", headers=hdr, timeout=timeout)
        if resp.status_code == 401:
            raise Exception("Sandbox token was revoked or regenerated on production. Please get the new token.")
        if resp.status_code != 200:
            raise Exception(f"Production returned HTTP {resp.status_code} for {path}")
        try:
            return resp.json()
        except Exception:
            raise Exception(f"Production returned non-JSON response for {path} (body: {resp.text[:200]!r})")

    try:
        # Step 1: Get table list + counts
        _refresh_progress.update(step="Fetching table list from production...", percent=10)
        tables_data = _prod_get("/api/admin/sandbox/export/tables")
        tables = tables_data.get("tables", {})
        total_records = tables_data.get("total_records", 0)

        # Exclude tables staging manages itself
        inspector = sa_inspect(engine)
        staging_tables = set(inspector.get_table_names())
        tables_to_write = [
            t for t in tables.keys()
            if t in staging_tables and t not in SKIP_TABLES and t != "sync_settings"
        ]

        _refresh_progress.update(
            step=f"Found {total_records} records across {len(tables_to_write)} tables. Starting import...",
            percent=15, detail=f"{total_records} total records"
        )

        from sqlalchemy import text
        lead_count = 0
        progress_per_table = 80 / max(len(tables_to_write), 1)
        current_progress = 15

        # Step 2: Per-table export + write
        for i, table_name in enumerate(tables_to_write):
            row_count = tables.get(table_name, 0)
            _refresh_progress.update(
                step=f"[{i+1}/{len(tables_to_write)}] Pulling {table_name} ({row_count} rows)...",
                percent=int(current_progress),
            )

            # Fetch this table from prod
            try:
                tdata = _prod_get(f"/api/admin/sandbox/export/table/{table_name}", timeout=30)
                rows = tdata.get("rows", [])
            except Exception as e:
                logger.warning(f"Sandbox refresh: skipped {table_name}: {e}")
                current_progress += progress_per_table
                continue

            # Write to staging — each table is its own transaction boundary
            try:
                db.execute(text(f'TRUNCATE TABLE "{table_name}" CASCADE'))
                if rows:
                    table_obj = models.Base.metadata.tables.get(table_name)
                    if table_obj is not None:
                        staging_cols = {c.name for c in table_obj.columns}
                        clean_rows = [{k: v for k, v in r.items() if k in staging_cols} for r in rows]
                        if clean_rows:
                            db.execute(table_obj.insert(), clean_rows)
                db.commit()  # Commit each table independently
                if table_name == "leads":
                    lead_count = len(rows)
            except Exception as e:
                db.rollback()  # Rollback so next table starts with a clean transaction
                logger.warning(f"Sandbox refresh: write failed for {table_name}: {e}")

            current_progress += progress_per_table

        # Commit
        db.commit()

        settings = _get_or_create_sync_settings(db)
        settings.sandbox_last_refresh_at = datetime.now(timezone.utc)
        settings.sandbox_last_refresh_status = "success"
        settings.sandbox_refresh_lead_count = lead_count
        db.commit()

        _refresh_progress.update(
            status="done", step="✅ Refresh complete!",
            percent=100, lead_count=lead_count,
            finished_at=datetime.now(timezone.utc).isoformat(),
        )
        logger.info(f"Sandbox refresh complete: {lead_count} leads, {len(tables_to_write)} tables")

    except Exception as e:
        db.rollback()
        error_msg = str(e)
        logger.error(f"Sandbox refresh failed: {error_msg}")
        try:
            settings = _get_or_create_sync_settings(db)
            settings.sandbox_last_refresh_status = "failed"
            db.commit()
        except Exception:
            pass
        _refresh_progress.update(
            status="failed", step="❌ Refresh failed",
            error=error_msg,
            finished_at=datetime.now(timezone.utc).isoformat(),
        )
    finally:
        db.close()
        _refresh_lock.release()


@router.post("/refresh")
def trigger_refresh(
    body: dict,
    db: Session = Depends(get_db),
    admin: dict = Depends(require_super_admin),
):
    """Trigger a mirror-mode refresh from production (staging only)."""
    _require_staging()

    # Verify confirmation
    if body.get("confirm") != "REFRESH":
        raise HTTPException(status_code=400, detail="Type REFRESH to confirm.")

    # Check connection
    settings = _get_or_create_sync_settings(db)
    if not settings.sandbox_prod_url or not settings.sandbox_prod_token:
        raise HTTPException(status_code=400, detail="Not connected to production. Set up the connection first.")

    # Concurrency guard
    if not _refresh_lock.acquire(blocking=False):
        raise HTTPException(status_code=423, detail="A refresh is already in progress.")

    try:
        prod_url = decrypt_token(settings.sandbox_prod_url)
        token = decrypt_token(settings.sandbox_prod_token)
    except Exception:
        _refresh_lock.release()
        raise HTTPException(status_code=500, detail="Failed to decrypt stored connection details.")

    # Reset progress
    global _refresh_progress
    _refresh_progress = {
        "status": "running", "step": "Starting...", "percent": 0,
        "detail": "", "started_at": datetime.now(timezone.utc).isoformat(),
        "finished_at": None, "lead_count": 0, "error": None,
    }

    # Run in background thread
    thread = threading.Thread(target=_do_refresh, args=(prod_url, token), daemon=True)
    thread.start()

    logger.info(f"Sandbox refresh triggered by {admin.get('email')}")
    return {"success": True, "message": "Refresh started. Poll /status for progress."}


# ── Status (Progress Polling) ────────────────────────────────────────────────

@router.get("/status")
def get_refresh_status(
    admin: dict = Depends(require_super_admin),
):
    """Get current refresh progress (staging only)."""
    _require_staging()
    return _refresh_progress


# ── Generate Synthetic Data ──────────────────────────────────────────────────

@router.post("/generate")
def generate_synthetic(
    body: dict,
    db: Session = Depends(get_db),
    admin: dict = Depends(require_super_admin),
):
    """Generate synthetic lead data (staging only). No prod connection needed."""
    _require_staging()

    count = body.get("count", 100)
    if count not in (100, 500, 1000, 2000):
        raise HTTPException(status_code=400, detail="Count must be 100, 500, 1000, or 2000.")

    if body.get("confirm") != "GENERATE":
        raise HTTPException(status_code=400, detail="Type GENERATE to confirm.")

    from faker import Faker
    fake = Faker()

    # Ensure pods exist
    pod_a = db.query(models.Pod).filter(models.Pod.name == "Sales Pod A").first()
    if not pod_a:
        pod_a = models.Pod(name="Sales Pod A")
        db.add(pod_a)
    pod_b = db.query(models.Pod).filter(models.Pod.name == "Sales Pod B").first()
    if not pod_b:
        pod_b = models.Pod(name="Sales Pod B")
        db.add(pod_b)
    db.flush()

    pods = [pod_a, pod_b]
    statuses = ["Lead Assigned", "Research", "Calling", "Meeting Scheduled"]
    created = 0

    for i in range(count):
        pod = pods[i % 2]
        lead = models.Lead(
            sf_lead_id=f"SYNTH_{uuid.uuid4().hex[:15].upper()}",
            first_name=fake.first_name(),
            last_name=fake.last_name(),
            email=f"synthetic_{i}@staging.test",
            phone=fake.numerify('##########') if i % 3 != 0 else None,
            company=fake.company(),
            title=fake.job(),
            status=statuses[i % len(statuses)],
            lead_source="synthetic",
            pod_id=pod.id,
            city=fake.city(),
            state=fake.state_abbr(),
            country="US",
            industry=fake.bs().title(),
        )
        db.add(lead)
        created += 1

    db.commit()

    settings = _get_or_create_sync_settings(db)
    settings.sandbox_last_refresh_at = datetime.now(timezone.utc)
    settings.sandbox_last_refresh_status = "success"
    settings.sandbox_refresh_lead_count = created
    db.commit()

    logger.info(f"Synthetic data: {created} leads generated by {admin.get('email')}")
    return {"success": True, "message": f"Generated {created} synthetic leads.", "count": created}


# ── Clear Data ───────────────────────────────────────────────────────────────

@router.post("/clear")
def clear_staging_data(
    body: dict,
    db: Session = Depends(get_db),
    admin: dict = Depends(require_super_admin),
):
    """Clear all staging data except users and config (staging only)."""
    _require_staging()

    if body.get("confirm") != "CLEAR":
        raise HTTPException(status_code=400, detail="Type CLEAR to confirm.")

    from sqlalchemy import text

    # Tables to clear (order matters for FK constraints)
    clear_tables = [
        "lead_attachments", "lead_email_activity", "email_threads",
        "dialer_calls", "call_logs", "notes", "tasks",
        "lead_status_logs", "salesforce_integration_logs",
        "user_activity_logs", "user_activity_daily_summary",
        "login_logs", "feedback", "company_research",
    ]

    # Clear lead_assignments (association table)
    try:
        db.execute(text("DELETE FROM lead_assignments"))
    except Exception as e:
        logger.warning(f"Clear lead_assignments: {e}")

    # Clear dependent tables first, then leads
    cleared = []
    for table_name in clear_tables:
        try:
            db.execute(text(f'TRUNCATE TABLE "{table_name}" CASCADE'))
            cleared.append(table_name)
        except Exception as e:
            logger.warning(f"Clear {table_name}: {e}")

    # Clear leads last
    try:
        db.execute(text('TRUNCATE TABLE "leads" CASCADE'))
        cleared.append("leads")
    except Exception as e:
        logger.warning(f"Clear leads: {e}")

    db.commit()
    logger.info(f"Staging data cleared by {admin.get('email')}: {cleared}")
    return {"success": True, "message": f"Cleared {len(cleared)} tables.", "tables": cleared}


# ── Environment Info ─────────────────────────────────────────────────────────

@router.get("/env")
def get_environment_info(
    admin: dict = Depends(require_super_admin),
):
    """Return environment detection info for frontend UI logic."""
    return {
        "is_staging": _is_staging(),
        "environment": "staging" if _is_staging() else "production",
        "self_test_enabled": os.getenv("SANDBOX_ALLOW_SELF_TEST", "").lower() in ("true", "1"),
    }
