#!/usr/bin/env node
// ============================================================================
// sync-version.mjs
// ============================================================================
// Reads the single canonical `VERSION` file at the repo root and fans it out
// to the generated modules the frontend bundles import from, so the version/
// brand string is never hand-edited in more than one place.
//
// Run this every time VERSION is bumped (see docs/AGENT_PROTOCOL.md Rule 15).
// After running, two spots still need a manual one-line edit — this script
// prints exactly what to change and where:
//   - frontend/manifest.json's "description" field (static JSON, no script tag)
//   - backend/config.py's APP_VERSION constant (Python can't import a
//     JS-generated file; a cross-runtime read isn't worth it for one string)
//
// Usage: node scripts/sync-version.mjs
// ============================================================================

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));

const APP_VERSION = readFileSync(join(ROOT, 'VERSION'), 'utf8').trim();
const BRAND_NAME = 'RCM';
const POWERED_BY = 'Powered by RCM';
const BRAND_TAGLINE = `${BRAND_NAME} · ${POWERED_BY}`;

const HEADER = `// AUTO-GENERATED by scripts/sync-version.mjs from /VERSION — do not hand-edit.\n`;

// ── frontend-react (Vite/ES module) ──────────────────────────────────────────
const reactOut = join(ROOT, 'frontend-react/src/generated/version.js');
mkdirSync(dirname(reactOut), { recursive: true });
writeFileSync(
  reactOut,
  `${HEADER}export const APP_VERSION = ${JSON.stringify(APP_VERSION)};\n` +
  `export const BRAND_NAME = ${JSON.stringify(BRAND_NAME)};\n` +
  `export const POWERED_BY = ${JSON.stringify(POWERED_BY)};\n` +
  `export const BRAND_TAGLINE = ${JSON.stringify(BRAND_TAGLINE)};\n`
);

// ── classic frontend (plain <script>, no module system) ──────────────────────
const classicOut = join(ROOT, 'frontend/js/generated-version.js');
writeFileSync(
  classicOut,
  `${HEADER}window.__APP_VERSION__ = ${JSON.stringify(APP_VERSION)};\n` +
  `window.__BRAND_NAME__ = ${JSON.stringify(BRAND_NAME)};\n` +
  `window.__POWERED_BY__ = ${JSON.stringify(POWERED_BY)};\n` +
  `window.__BRAND_TAGLINE__ = ${JSON.stringify(BRAND_TAGLINE)};\n`
);

console.log(`✓ Synced VERSION (${APP_VERSION}) to:`);
console.log(`  - ${reactOut}`);
console.log(`  - ${classicOut}`);
console.log(`\nManual one-line edits still needed (residual, no shared runtime):`);
console.log(`  - frontend/manifest.json: "description" field, if the version is mentioned`);
console.log(`  - backend/config.py: APP_VERSION = "${APP_VERSION}"`);
