// AUTO-GENERATED by scripts/sync-version.mjs from /VERSION — do not hand-edit.
window.__APP_VERSION__ = "11.0.0";
window.__BRAND_NAME__ = "RCM";
window.__POWERED_BY__ = "Powered by RCM";
window.__BRAND_TAGLINE__ = "RCM · Powered by RCM";
